import assert from "node:assert/strict";
import path from "node:path";
import { pathToFileURL } from "node:url";

const workspace = path.resolve(process.argv[2] ?? ".");
const { TTLCache } = await import(pathToFileURL(path.join(workspace, "src", "ttlCache.mjs")));
let now = 1000;
const cache = new TTLCache(() => now);
cache.set("zero", 0, 10);
cache.set("false", false, 20);
cache.set("undefined", undefined, 30);
assert.equal(cache.size, 3);
assert.equal(cache.get("zero"), 0);
assert.equal(cache.get("undefined"), undefined);
assert.equal(cache.has("undefined"), true);
now = 1010;
assert.equal(cache.get("zero"), undefined);
assert.equal(cache.has("zero"), false);
assert.equal(cache.size, 2);
cache.set("false", "overwritten", 5);
now = 1015;
assert.equal(cache.has("false"), false);
assert.equal(cache.prune(), 0);
assert.equal(cache.size, 1);
now = 1030;
assert.equal(cache.prune(), 1);
assert.equal(cache.size, 0);
cache.set("delete", 1, 10);
assert.equal(cache.delete("delete"), true);
assert.equal(cache.delete("delete"), false);
for (const ttl of [0, -1, Infinity, NaN]) assert.throws(() => cache.set("bad", 1, ttl), /ttl/i);
console.log("ttl-cache: sealed grader passed");
